// Package: com.lightningkite.template.utils
// Generated by Khrysalis - this file will be overwritten.

//! Declares com.lightningkite.template.utils.Preferences
export let _Preferences: Storage;
export function getPreferences(): Storage {
    if (_Preferences !== undefined) return _Preferences
    else {
        const r = localStorage
        _Preferences = r
        return r
    }
}

//! Declares com.lightningkite.template.utils.SecurePreferences
export let _SecurePreferences: Storage;
export function getSecurePreferences(): Storage {
    if (_SecurePreferences !== undefined) return _SecurePreferences
    else {
        const r = localStorage as Storage
        _SecurePreferences = r
        return r
    }
}
