// Package: com.lightningkite.template.utils
// Generated by Khrysalis - this file will be overwritten.
import { getSecurePreferences } from './preferences'
import { runOrNull } from '@lightningkite/khrysalis-runtime'

//! Declares com.lightningkite.template.utils.PreferenceKeys
export class PreferenceKeys {
    private constructor() {
        this.serverKey = "server";
        this.sessionKey = "session";
    }
    public static INSTANCE = new PreferenceKeys();
    
    public readonly serverKey: string;
    public readonly sessionKey: string;
    
    //! Declares com.lightningkite.template.utils.PreferenceKeys.server
    public get server(): (string | null) { return (getSecurePreferences().getItem(this.serverKey) ?? null); }
    public set server(value: (string | null)) {
        const it_2 = value;
        if (it_2 !== null) {
            getSecurePreferences().setItem(this.serverKey, it_2);
        } else {
            getSecurePreferences().removeItem(this.serverKey)
        }
    }
    
    //! Declares com.lightningkite.template.utils.PreferenceKeys.session
    public get session(): (string | null) { return (getSecurePreferences().getItem(this.sessionKey) ?? null); }
    public set session(value: (string | null)) {
        const it_13 = value;
        if (it_13 !== null) {
            getSecurePreferences().setItem(this.sessionKey, it_13);
        } else {
            getSecurePreferences().removeItem(this.sessionKey)
        }
    }
    
}