// Package: com.lightningkite.template.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwiftPlus
import Foundation

public protocol HasTitle: AnyObject {
    
    var title: String { get }
    
}

