// Package: com.lightningkite.template.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation
import XmlToXibRuntime

public final class LandingVG : ViewGenerator {
    public unowned var root: ValueSubject<Array<ViewGenerator>>
    public unowned var stack: ValueSubject<Array<ViewGenerator>>
    public init(root: ValueSubject<Array<ViewGenerator>>, stack: ValueSubject<Array<ViewGenerator>>) {
        self.root = root
        self.stack = stack
        //Necessary properties should be initialized now
    }
    
    
    //--- Properties
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        
        let xml = LandingBinding()
        
        //--- Set Up xml.background (overwritten on flow generation)
        
        //--- Set Up xml.anonLogin (overwritten on flow generation)
        xml.anonLogin.onClick { () -> Void in self.anonLoginClick() }
        
        //--- Set Up xml.signUp (overwritten on flow generation)
        xml.signUp.onClick { () -> Void in self.signUpClick() }
        
        //--- Set Up xml.logIn (overwritten on flow generation)
        xml.logIn.onClick { () -> Void in self.logInClick() }
        
        //--- Generate End (overwritten on flow generation)
        
        return xml.root
    }
    
    
    
    //--- Actions
    
    public func anonLoginClick() -> Void {
        self.stack.push(AppExplanationVG(root: self.root, stack: self.stack))
    }
    
    public func signUpClick() -> Void {
        self.stack.push(LogInVG(root: self.root, stack: self.stack))
    }
    
    public func logInClick() -> Void {
        self.stack.push(LogInVG(root: self.root, stack: self.stack))
    }
    
    
    //--- Body End
}

