// Package: com.lightningkite.template.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation
import XmlToXibRuntime

public final class LoadingDialogVG : ViewGenerator {
    public init() {
        //Necessary properties should be initialized now
    }
    
    
    //--- Properties
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        
        let xml = LoadingDialogBinding()
        
        //--- Generate End (overwritten on flow generation)
        
        return xml.root
    }
    
    
    
    //--- Actions
    
    
    //--- Body End
}

