// Package: com.lightningkite.template.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation
import XmlToXibRuntime

public final class TermsVG : ViewGenerator {
    public var onResult: () -> Void
    public init(onResult: @escaping () -> Void) {
        self.onResult = onResult
        self.agreed = ValueSubject(false)
        //Necessary properties should be initialized now
    }
    
    
    public let agreed: ValueSubject<Bool>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        
        let xml = TermsBinding()
        
        //--- Set Up xml.agree
        self.agreed.bind(xml.agree)
        
        //--- Set Up xml.submit
        self.agreed.subscribeAutoDispose(xml.submit, \UIControl.isEnabled)
        xml.submit.onClick { () -> Void in if self.agreed.value {
            self.onResult()
        } }
        
        //--- Generate End (overwritten on flow generation)
        
        return xml.root
    }
    
    
    
    //--- Actions
    
    //--- Action submitClick
    
    
    //--- Body End
}

