// Package: com.lightningkite.template.models
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import RxSwiftPlus
import Foundation

public final class UserSession : AbstractUserSession {
    private var _api: Api
    override public var api: Api { get { return self._api } set(value) { self._api = value } }
    private var _userToken: String
    override public var userToken: String { get { return self._userToken } set(value) { self._userToken = value } }
    override public init(_ api: Api, userToken: String) {
        self._api = api
        self._userToken = userToken
        super.init(api, userToken: userToken)
        //Necessary properties should be initialized now
    }
    
}

public final class Session {
    public var anon: AnonymousSession
    public var user: UserSession?
    public init(anon: AnonymousSession, user: UserSession? = nil) {
        self.anon = anon
        self.user = user
        //Necessary properties should be initialized now
    }
    
    public var api: Api {
        get { return self.anon.api }
    }
    public var userToken: String? {
        get { return self.user?.userToken }
    }
}

public final class AnonymousSession : AbstractAnonymousSession {
    override public init(_ api: Api) {
        super.init(api)
        //Necessary properties should be initialized now
    }
    
}
