use_frameworks!

platform :ios, '11.0'

target 'IosProject' do

  pod 'KeychainSwift'
  pod 'Firebase/Messaging'
  pod 'RxSwift', :git => 'https://github.com/lightningkite/RxSwift.git', :branch => 'main'
  pod 'RxSwiftPlus/ViewGeneratorFcm', :path => '../../RxSwiftPlus/RxSwiftPlus.podspec'
  pod 'RxSwiftPlus/BindingsXmlToXibRuntimeKhrysalis', :path => '../../RxSwiftPlus/RxSwiftPlus.podspec'
  pod 'RxSwiftPlus/Http', :path => '../../RxSwiftPlus/RxSwiftPlus.podspec'
  pod 'XmlToXibRuntime', :path => '../../android-layout-translator/XmlToXibRuntime.podspec'
  pod 'LightningServer', :git =>'https://github.com/lightningkite/lightning-server', :branch => 'master'
  pod 'KhrysalisRuntime', :path => '../../khrysalis/KhrysalisRuntime.podspec'
  pod "RxCoreLocation", :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'master'

  # pod 'RxSwift', :git => 'https://github.com/lightningkite/RxSwift.git', :branch => 'main'
  # pod 'RxSwiftPlus', :git => 'https://github.com/lightningkite/RxSwiftPlus.git', :branch => 'master'
  # pod 'LightningServer', :git =>'https://github.com/lightningkite/lightning-server', :branch => 'master'
  # pod 'XmlToXibRuntime', :git => 'https://github.com/lightningkite/android-layout-translator.git', :branch => 'master'
  # pod 'KhrysalisRuntime', :git => 'https://github.com/lightningkite/khrysalis.git', :branch => 'master'
  # pod "RxCoreLocation", :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'master'
end
