// Package: com.lightningkite.template
// Generated by Khrysalis - this file will be overwritten.
import { FcmToken } from './models'
import { PropChain } from '@lightningkite/lightning-server'

//! Declares com.lightningkite.template.prepareFcmTokenFields
export function prepareFcmTokenFields(): void {
    ;
    ;
}
//! Declares com.lightningkite.template._id>com.lightningkite.lightningdb.PropChaincom.lightningkite.template._id.K, com.lightningkite.template.FcmToken
export function xPropChain_idGet<K>(this_: PropChain<K, FcmToken>): PropChain<K, string> { return this_.get<string>("_id"); }

//! Declares com.lightningkite.template.user>com.lightningkite.lightningdb.PropChaincom.lightningkite.template.user.K, com.lightningkite.template.FcmToken
export function xPropChainUserGet<K>(this_: PropChain<K, FcmToken>): PropChain<K, string> { return this_.get<string>("user"); }

