// Package: com.lightningkite.template
// Generated by Khrysalis - this file will be overwritten.
import { User } from './models'
import { Instant } from '@js-joda/core'
import { PropChain } from '@lightningkite/lightning-server'

//! Declares com.lightningkite.template.prepareUserFields
export function prepareUserFields(): void {
    ;
    ;
    ;
    ;
    ;
    ;
}
//! Declares com.lightningkite.template._id>com.lightningkite.lightningdb.PropChaincom.lightningkite.template._id.K, com.lightningkite.template.User
export function xPropChain_idGet<K>(this_: PropChain<K, User>): PropChain<K, string> { return this_.get<string>("_id"); }

//! Declares com.lightningkite.template.email>com.lightningkite.lightningdb.PropChaincom.lightningkite.template.email.K, com.lightningkite.template.User
export function xPropChainEmailGet<K>(this_: PropChain<K, User>): PropChain<K, string> { return this_.get<string>("email"); }

//! Declares com.lightningkite.template.termsAgreed>com.lightningkite.lightningdb.PropChaincom.lightningkite.template.termsAgreed.K, com.lightningkite.template.User
export function xPropChainTermsAgreedGet<K>(this_: PropChain<K, User>): PropChain<K, Instant> { return this_.get<Instant>("termsAgreed"); }

//! Declares com.lightningkite.template.isSuperUser>com.lightningkite.lightningdb.PropChaincom.lightningkite.template.isSuperUser.K, com.lightningkite.template.User
export function xPropChainIsSuperUserGet<K>(this_: PropChain<K, User>): PropChain<K, boolean> { return this_.get<boolean>("isSuperUser"); }

//! Declares com.lightningkite.template.subscriptionId>com.lightningkite.lightningdb.PropChaincom.lightningkite.template.subscriptionId.K, com.lightningkite.template.User
export function xPropChainSubscriptionIdGet<K>(this_: PropChain<K, User>): PropChain<K, (string | null)> { return this_.get<(string | null)>("subscriptionId"); }

//! Declares com.lightningkite.template.customerId>com.lightningkite.lightningdb.PropChaincom.lightningkite.template.customerId.K, com.lightningkite.template.User
export function xPropChainCustomerIdGet<K>(this_: PropChain<K, User>): PropChain<K, (string | null)> { return this_.get<(string | null)>("customerId"); }

