// Package: com.lightningkite.template.utils
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public final class PreferenceKeys {
    public init() {
        self.serverKey = "server"
        self.sessionKey = "session"
        //Necessary properties should be initialized now
    }
    public static let INSTANCE = PreferenceKeys()
    
    public let serverKey: String
    public let sessionKey: String
    
    public var server: String? {
        get { return (SecurePreferences.string(forKey: self.serverKey) ?? nil) }
        set(value) {
            if let it = (value) {
                SecurePreferences.set(it, forKey: self.serverKey)
            } else {
                SecurePreferences.removeObject(forKey: self.serverKey)
            }
        }
    }
    public var session: String? {
        get { return (SecurePreferences.string(forKey: self.sessionKey) ?? nil) }
        set(value) {
            if let it = (value) {
                SecurePreferences.set(it, forKey: self.sessionKey)
            } else {
                SecurePreferences.removeObject(forKey: self.sessionKey)
            }
        }
    }
}
