// Package: com.lightningkite.template.vg
// Generated by Khrysalis - this file will be overwritten.
import { LoadingDialogBinding } from '../../resources/layouts/LoadingDialogBinding'
import { ViewGenerator } from '@lightningkite/rxjs-plus'

//! Declares com.lightningkite.template.vg.LoadingDialogVG
export class LoadingDialogVG implements ViewGenerator {
    public static implementsViewGenerator = true;
    public constructor() {
    }
    
    
    //--- Properties
    
    public generate(dependency: Window): HTMLElement {
        
        const xml = LoadingDialogBinding.inflate();
        
        //--- Generate End (overwritten on flow generation)
        
        return xml.root;
    }
    
    
    
    //--- Actions
    
    
    //--- Body End
}
