// Package: com.lightningkite.template
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import LightningServer
import Foundation

public func prepareFcmTokenFields() -> Void {
    
    
}
public extension PropChain where To == FcmToken {
    var _id: PropChain<From, String> {
        get { return self.get(prop: FcmToken._idProp) }
    }
}
public extension PropChain where To == FcmToken {
    var user: PropChain<From, UUID> {
        get { return self.get(prop: FcmToken.userProp) }
    }
}

