// Package: com.lightningkite.template
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public func prepareModels() -> Void {
    prepareUserFields()
    prepareFcmTokenFields()
}

